server:
  port: 8070
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: cloud-demo-user
  rabbitmq:
    host: 42.192.81.74
    port: 5672
    username: admin
    password: 123456
    virtualHost: '/'
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    instance:
      hostname: 127.0.0.1
      prefer-ip-address: true
      instance-id: 127.0.0.1:8070