server:
  port: 8060
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: cloud-demo-data
  elasticsearch:
    address: localhost:9200
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    instance:
      hostname: 127.0.0.1
      prefer-ip-address: true
      instance-id: 127.0.0.1:8060



#data source0
data:
  sharding:
    ds[0]:
      dcName: study
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/study?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123
      slaveDs[0]:
        dcName: studySlave
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3307/study?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123
    ##ds[1]:
    ## names: ds1
    ## type: com.alibaba.druid.pool.DruidDataSource
    ## url: jdbc:mysql://127.0.0.1:3306/dc_sdk?serverTimezone=GMT%2B8&useSSL=false
  ##  username: root
  ##  password: root
#sql???
logging:
  level:
    com:
      hyc:
        dao: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
