server:
  port: 8090
spring:
  application:
    name: cloud-demo-mq
  rabbitmq:
    host: 42.192.81.74
    port: 5672
    username: admin
    password: 123456
    virtualHost: '/'
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    instance:
      hostname: 127.0.0.1
      prefer-ip-address: true
      instance-id: 127.0.0.1:8060

